name: production

on:
  push:
    branches:
      - docker-test
  pull_request:
    branches:
      - docker-test
    
jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build and push the tagged docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: fundacao-solidaria-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Updates Dockerrun.aws.json
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: fundacao-solidaria-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          sed -i "s/ECR_REGISTRY/${ECR_REGISTRY}/g" Dockerrun.aws.json
          sed -i "s/ECR_REPOSITORY/${ECR_REPOSITORY}/g" Dockerrun.aws.json
          sed -i "s/IMAGE_TAG/${IMAGE_TAG}/g" Dockerrun.aws.json

      - name: Generate deployment package
        run: zip -r deploy.zip .elasticbeanstalk Dockerrun.aws.json
        
      - name: Beanstalk Deploy for app
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.SECRET_ACCESS_KEY }}
          application_name: fundacao-solidaria-api
          environment_name: fundacao-solidaria-api
          region: us-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

      - name: Deployed!
        run: echo App deployed to ELB
